import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Provider from '@/components/Provider';
import Header from '@/components/Header';
import './globals.css';

const poppins = Poppins({ weight: ['400', '500', '600'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'AskiGaming',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#F6F8FC]`}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
